version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend-image
    build:
      context: ./backend
    ports:
      - "8000:8000"

  # Define any other services (e.g., databases) here
